package webservice;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 8/11/2017 5:10:09 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class    DiscountProductInfo implements KvmSerializable {
    
    public VectorDiscountAgreementInfo discountAgreements;
    public int productId;
    public boolean activeDiscountsFound;
    public int totalActiveDiscounts;
    public int activeArticleDiscounts;
    public int activeMixedMatches;
    public int activeDiscountAgreements;
    
    public DiscountProductInfo(){}
    
    public DiscountProductInfo(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("DiscountAgreements"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("DiscountAgreements");
            discountAgreements = new VectorDiscountAgreementInfo(j);
        }
        if (soapObject.hasProperty("ProductId"))
        {
            Object obj = soapObject.getProperty("ProductId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                productId = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                productId = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("ActiveDiscountsFound"))
        {
            Object obj = soapObject.getProperty("ActiveDiscountsFound");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                activeDiscountsFound = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                activeDiscountsFound = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("TotalActiveDiscounts"))
        {
            Object obj = soapObject.getProperty("TotalActiveDiscounts");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                totalActiveDiscounts = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                totalActiveDiscounts = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("ActiveArticleDiscounts"))
        {
            Object obj = soapObject.getProperty("ActiveArticleDiscounts");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                activeArticleDiscounts = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                activeArticleDiscounts = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("ActiveMixedMatches"))
        {
            Object obj = soapObject.getProperty("ActiveMixedMatches");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                activeMixedMatches = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                activeMixedMatches = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("ActiveDiscountAgreements"))
        {
            Object obj = soapObject.getProperty("ActiveDiscountAgreements");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                activeDiscountAgreements = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                activeDiscountAgreements = (Integer) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return discountAgreements;
            case 1:
                return productId;
            case 2:
                return activeDiscountsFound;
            case 3:
                return totalActiveDiscounts;
            case 4:
                return activeArticleDiscounts;
            case 5:
                return activeMixedMatches;
            case 6:
                return activeDiscountAgreements;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 7;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "DiscountAgreements";
                break;
            case 1:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "ProductId";
                break;
            case 2:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "ActiveDiscountsFound";
                break;
            case 3:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "TotalActiveDiscounts";
                break;
            case 4:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "ActiveArticleDiscounts";
                break;
            case 5:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "ActiveMixedMatches";
                break;
            case 6:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "ActiveDiscountAgreements";
                break;
        }
    }
    
//    @Override //    public String getInnerText() { //        return null; //    } // // //    @Override //    public void setInnerText(String s) { //    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
