package webservice;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 8/16/2017 5:54:08 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;

import java.lang.*;
import java.util.Hashtable;

import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class LocationLevel5Filter implements KvmSerializable {

    public int itemId;
    /*  public int storeId;
      public int locationLevel1Id;
      public int locationLevel2Id;
      public int locationLevel3Id;*/
    public int locationLevel4Id;
    /*public String locationLevel1Code;
   public String locationLevel2Code;
   public String locationLevel3Code;
   public String locationLevel4Code;*/
    //   public String locationLevel5Code;
    public String locationCode;

    //    public String uniqueLocationCode;
//    public String description;
//    public Byte maxStoragePositions;
//
    public LocationLevel5Filter() {
    }

    public LocationLevel5Filter(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("ItemId"))
        {
            Object obj = soapObject.getProperty("ItemId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                itemId = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                itemId = (Integer) obj;
            }
        }
//        if (soapObject.hasProperty("StoreId"))
//        {
//            Object obj = soapObject.getProperty("StoreId");
//            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
//                SoapPrimitive j =(SoapPrimitive) obj;
//                storeId = Integer.parseInt(j.toString());
//            }else if (obj!= null && obj instanceof Number){
//                storeId = (Integer) obj;
//            }
//        }
//        if (soapObject.hasProperty("LocationLevel1Id"))
//        {
//            Object obj = soapObject.getProperty("LocationLevel1Id");
//            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
//                SoapPrimitive j =(SoapPrimitive) obj;
//                locationLevel1Id = Integer.parseInt(j.toString());
//            }else if (obj!= null && obj instanceof Number){
//                locationLevel1Id = (Integer) obj;
//            }
//        }
//        if (soapObject.hasProperty("LocationLevel2Id"))
//        {
//            Object obj = soapObject.getProperty("LocationLevel2Id");
//            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
//                SoapPrimitive j =(SoapPrimitive) obj;
//                locationLevel2Id = Integer.parseInt(j.toString());
//            }else if (obj!= null && obj instanceof Number){
//                locationLevel2Id = (Integer) obj;
//            }
//        }
//        if (soapObject.hasProperty("LocationLevel3Id"))
//        {
//            Object obj = soapObject.getProperty("LocationLevel3Id");
//            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
//                SoapPrimitive j =(SoapPrimitive) obj;
//                locationLevel3Id = Integer.parseInt(j.toString());
//            }else if (obj!= null && obj instanceof Number){
//                locationLevel3Id = (Integer) obj;
//            }
//        }
        if (soapObject.hasProperty("LocationLevel4Id")) {
            Object obj = soapObject.getProperty("LocationLevel4Id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                locationLevel4Id = Integer.parseInt(j.toString());
            } else if (obj != null && obj instanceof Number) {
                locationLevel4Id = (Integer) obj;
            }
        }
//        if (soapObject.hasProperty("LocationLevel1Code"))
//        {
//            Object obj = soapObject.getProperty("LocationLevel1Code");
//            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
//                SoapPrimitive j =(SoapPrimitive) obj;
//                locationLevel1Code = j.toString();
//            }else if (obj!= null && obj instanceof String){
//                locationLevel1Code = (String) obj;
//            }
//        }
//        if (soapObject.hasProperty("LocationLevel2Code"))
//        {
//            Object obj = soapObject.getProperty("LocationLevel2Code");
//            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
//                SoapPrimitive j =(SoapPrimitive) obj;
//                locationLevel2Code = j.toString();
//            }else if (obj!= null && obj instanceof String){
//                locationLevel2Code = (String) obj;
//            }
//        }
//        if (soapObject.hasProperty("LocationLevel3Code"))
//        {
//            Object obj = soapObject.getProperty("LocationLevel3Code");
//            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
//                SoapPrimitive j =(SoapPrimitive) obj;
//                locationLevel3Code = j.toString();
//            }else if (obj!= null && obj instanceof String){
//                locationLevel3Code = (String) obj;
//            }
//        }
//        if (soapObject.hasProperty("LocationLevel4Code"))
//        {
//            Object obj = soapObject.getProperty("LocationLevel4Code");
//            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
//                SoapPrimitive j =(SoapPrimitive) obj;
//                locationLevel4Code = j.toString();
//            }else if (obj!= null && obj instanceof String){
//                locationLevel4Code = (String) obj;
//            }
//        }
/*        if (soapObject.hasProperty("LocationLevel5Code"))
        {
            Object obj = soapObject.getProperty("LocationLevel5Code");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                locationLevel5Code = j.toString();
            }else if (obj!= null && obj instanceof String){
                locationLevel5Code = (String) obj;
            }
        }*/
        if (soapObject.hasProperty("LocationCode")) {
            Object obj = soapObject.getProperty("LocationCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                locationCode = j.toString();
            } else if (obj != null && obj instanceof String) {
                locationCode = (String) obj;
            }
        }
//        if (soapObject.hasProperty("UniqueLocationCode"))
//        {
//            Object obj = soapObject.getProperty("UniqueLocationCode");
//            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
//                SoapPrimitive j =(SoapPrimitive) obj;
//                uniqueLocationCode = j.toString();
//            }else if (obj!= null && obj instanceof String){
//                uniqueLocationCode = (String) obj;
//            }
//        }
//        if (soapObject.hasProperty("Description"))
//        {
//            Object obj = soapObject.getProperty("Description");
//            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
//                SoapPrimitive j =(SoapPrimitive) obj;
//                description = j.toString();
//            }else if (obj!= null && obj instanceof String){
//                description = (String) obj;
//            }
//        }
//        if (soapObject.hasProperty("MaxStoragePositions"))
//        {
//            Object obj = soapObject.getProperty("MaxStoragePositions");
//            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
//                SoapPrimitive j =(SoapPrimitive) obj;
//                maxStoragePositions = Byte.parseByte(j.toString());
//            }else if (obj!= null && obj instanceof Byte){
//                maxStoragePositions = (Byte) obj;
//            }
//        }
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 2:
                return itemId;
//            case 1:
//                return storeId;
//            case 2:
//                return locationLevel1Id;
//            case 3:
//                return locationLevel2Id;
//            case 4:
//                return locationLevel3Id;
            case 1:
                return locationLevel4Id;
//            case 6:
//                return locationLevel1Code;
//            case 7:
//                return locationLevel2Code;
//            case 8:
//                return locationLevel3Code;
//            case 9:
//                return locationLevel4Code;
//            case 0:
//                return locationLevel5Code;
            case 0:
                return locationCode;
//            case 12:
//                return uniqueLocationCode;
//            case 13:
//                return description;
//            case 14:
//                return maxStoragePositions.toString();
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 2:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "ItemId";
                break;
/*            case 1:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "StoreId";
                break;
            case 2:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "LocationLevel1Id";
                break;
            case 3:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "LocationLevel2Id";
                break;
            case 4:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "LocationLevel3Id";
                break;

            case 6:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "LocationLevel1Code";
                break;
            case 7:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "LocationLevel2Code";
                break;
            case 8:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "LocationLevel3Code";
                break;
            case 9:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "LocationLevel4Code";
                break;*/
            /*case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "LocationLevel5Code";
                break;*/
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "LocationCode";
                break;
            case 1:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "LocationLevel4Id";
                break;
                /*            case 12:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "UniqueLocationCode";
                break;
            case 13:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Description";
                break;
            case 14:
                info.type = Byte.class;
                info.name = "MaxStoragePositions";
                break;*/
        }
    }

//    @Override //    public String getInnerText() { //        return null; //    } // // //    @Override //    public void setInnerText(String s) { //    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
