package webservice;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 8/16/2017 5:54:08 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;

import java.lang.*;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class LocationLevel2Filter implements KvmSerializable {
    
    public int storeId;
    public int locationLevel1Id;
    //public String code;
    
    public LocationLevel2Filter(){}
    
    public LocationLevel2Filter(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("StoreId"))
        {
            Object obj = soapObject.getProperty("StoreId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                storeId = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                storeId = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("LocationLevel1Id"))
        {
            Object obj = soapObject.getProperty("LocationLevel1Id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                locationLevel1Id = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                locationLevel1Id = (Integer) obj;
            }
        }
//        if (soapObject.hasProperty("Code"))
//        {
//            Object obj = soapObject.getProperty("Code");
//            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
//                SoapPrimitive j =(SoapPrimitive) obj;
//                code = j.toString();
//            }else if (obj!= null && obj instanceof String){
//                code = (String) obj;
//            }
//        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return storeId;
            case 1:
                return locationLevel1Id;
//            case 2:
//                return code;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 2;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "StoreId";
                break;
            case 1:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "LocationLevel1Id";
                break;
//            case 2:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "Code";
//                break;
        }
    }
    
//    @Override //    public String getInnerText() { //        return null; //    } // // //    @Override //    public void setInnerText(String s) { //    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
