package webservice;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 8/16/2017 5:54:09 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class ProductListRowInfoFroUpdate implements KvmSerializable {
    public int itemId;
    public int productListId;
    public double amount;
    public int productId;
    public int brandId;
    public int referenceNumber;
    public double pceGrossPrice;
    public String description;
    public double discountPrice;
    public double discountPercentage;

    /*public int companyId;
     public double totalNetPrice;
    public int parentProductListRowId;
    public int supplierId;
    public double totalGrossPrice;
    public WS_Enums.SalePriceType priceType;
    public double weightedTotalNetPrice;
    public long barcode;
    public long conversionId;
    public int createdByUserId;
    public String createdDateTime;
    public int lastModifiedByUserId;
    public String lastModifiedDateTime;*/


    public ProductListRowInfoFroUpdate() {
    }

    public ProductListRowInfoFroUpdate(SoapObject soapObject) {
        if (soapObject == null)
            return;
/*        if (soapObject.hasProperty("CompanyId")) {
            Object obj = soapObject.getProperty("CompanyId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                companyId = Integer.parseInt(j.toString());
            } else if (obj != null && obj instanceof Number) {
                companyId = (Integer) obj;
            }
        }*/
        if (soapObject.hasProperty("ProductListId")) {
            Object obj = soapObject.getProperty("ProductListId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                productListId = Integer.parseInt(j.toString());
            } else if (obj != null && obj instanceof Number) {
                productListId = (Integer) obj;
            }
        }
/*        if (soapObject.hasProperty("ParentProductListRowId")) {
            Object obj = soapObject.getProperty("ParentProductListRowId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                parentProductListRowId = Integer.parseInt(j.toString());
            } else if (obj != null && obj instanceof Number) {
                parentProductListRowId = (Integer) obj;
            }
        }*/
        if (soapObject.hasProperty("Amount")) {
            Object obj = soapObject.getProperty("Amount");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                amount = Double.parseDouble(j.toString());
            } else if (obj != null && obj instanceof Number) {
                amount = (Double) obj;
            }
        }
        if (soapObject.hasProperty("ProductId")) {
            Object obj = soapObject.getProperty("ProductId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                productId = Integer.parseInt(j.toString());
            } else if (obj != null && obj instanceof Number) {
                productId = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("BrandId")) {
            Object obj = soapObject.getProperty("BrandId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                brandId = Integer.parseInt(j.toString());
            } else if (obj != null && obj instanceof Number) {
                brandId = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("ReferenceNumber")) {
            Object obj = soapObject.getProperty("ReferenceNumber");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                referenceNumber = Integer.parseInt(j.toString());
            } else if (obj != null && obj instanceof Number) {
                referenceNumber = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("PceGrossPrice")) {
            Object obj = soapObject.getProperty("PceGrossPrice");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                pceGrossPrice = Double.parseDouble(j.toString());
            } else if (obj != null && obj instanceof Number) {
                pceGrossPrice = (Double) obj;
            }
        }
        if (soapObject.hasProperty("Description")) {
            Object obj = soapObject.getProperty("Description");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                description = j.toString();
            } else if (obj != null && obj instanceof String) {
                description = (String) obj;
            }
        }
        if (soapObject.hasProperty("DiscountPrice")) {
            Object obj = soapObject.getProperty("DiscountPrice");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                discountPrice = Double.parseDouble(j.toString());
            } else if (obj != null && obj instanceof Number) {
                discountPrice = (Double) obj;
            }
        }
        if (soapObject.hasProperty("DiscountPercentage")) {
            Object obj = soapObject.getProperty("DiscountPercentage");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                discountPercentage = Double.parseDouble(j.toString());
            } else if (obj != null && obj instanceof Number) {
                discountPercentage = (Double) obj;
            }
        }
        if (soapObject.hasProperty("ItemId")) {
            Object obj = soapObject.getProperty("ItemId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                itemId = Integer.parseInt(j.toString());
            } else if (obj != null && obj instanceof Number) {
                itemId = (Integer) obj;
            }
        }
     /*   if (soapObject.hasProperty("SupplierId")) {
            Object obj = soapObject.getProperty("SupplierId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                supplierId = Integer.parseInt(j.toString());
            } else if (obj != null && obj instanceof Number) {
                supplierId = (Integer) obj;
            }
        }


        if (soapObject.hasProperty("TotalGrossPrice")) {
            Object obj = soapObject.getProperty("TotalGrossPrice");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                totalGrossPrice = Double.parseDouble(j.toString());
            } else if (obj != null && obj instanceof Number) {
                totalGrossPrice = (Double) obj;
            }
        }
        if (soapObject.hasProperty("TotalNetPrice")) {
            Object obj = soapObject.getProperty("TotalNetPrice");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                totalNetPrice = Double.parseDouble(j.toString());
            } else if (obj != null && obj instanceof Number) {
                totalNetPrice = (Double) obj;
            }
        }
        */

/*

        if (soapObject.hasProperty("PriceType")) {
            Object obj = soapObject.getProperty("PriceType");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                priceType = WS_Enums.SalePriceType.fromString(j.toString());
            }
        }
        if (soapObject.hasProperty("WeightedTotalNetPrice")) {
            Object obj = soapObject.getProperty("WeightedTotalNetPrice");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                weightedTotalNetPrice = Double.parseDouble(j.toString());
            } else if (obj != null && obj instanceof Number) {
                weightedTotalNetPrice = (Double) obj;
            }
        }
        if (soapObject.hasProperty("Barcode")) {
            Object obj = soapObject.getProperty("Barcode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                barcode = Integer.parseInt(j.toString());
            } else if (obj != null && obj instanceof Number) {
                barcode = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("ConversionId")) {
            Object obj = soapObject.getProperty("ConversionId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                conversionId = Integer.parseInt(j.toString());
            } else if (obj != null && obj instanceof Number) {
                conversionId = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("CreatedByUserId")) {
            Object obj = soapObject.getProperty("CreatedByUserId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                createdByUserId = Integer.parseInt(j.toString());
            } else if (obj != null && obj instanceof Number) {
                createdByUserId = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("CreatedDateTime")) {
            Object obj = soapObject.getProperty("CreatedDateTime");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                createdDateTime = j.toString();
            } else if (obj != null && obj instanceof String) {
                createdDateTime = (String) obj;
            }
        }
        if (soapObject.hasProperty("LastModifiedByUserId")) {
            Object obj = soapObject.getProperty("LastModifiedByUserId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                lastModifiedByUserId = Integer.parseInt(j.toString());
            } else if (obj != null && obj instanceof Number) {
                lastModifiedByUserId = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("LastModifiedDateTime")) {
            Object obj = soapObject.getProperty("LastModifiedDateTime");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                lastModifiedDateTime = j.toString();
            } else if (obj != null && obj instanceof String) {
                lastModifiedDateTime = (String) obj;
            }
        }*/
       /*
*/
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return productListId;
            case 1:
                return amount;
            case 2:
                return productId;
            case 3:
                return description;
            case 4:
                return discountPrice;
            case 5:
                return discountPercentage;
            case 6:
                return referenceNumber;
            case 7:
                return pceGrossPrice;
            case 8:
                return itemId;
            case 9:
                return brandId;

/*
            case 1:
                return totalNetPrice;


            case 0:
                return companyId;
            case 2:
                return parentProductListRowId;

            case 6:
                return supplierId;

            case 9:
                return totalGrossPrice;

            case 14:
                return priceType.toString();
            case 15:
                return weightedTotalNetPrice;
            case 16:
                return barcode;
            case 17:
                return conversionId;
            case 18:
                return createdByUserId;
            case 19:
                return createdDateTime;
            case 20:
                return lastModifiedByUserId;
            case 21:
                return lastModifiedDateTime;*/
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 10;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {

            case 0:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "ProductListId";
                break;
            case 1:
                info.type = Double.class;
                info.name = "Amount";
                break;
            case 2:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "ProductId";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Description";
                break;
            case 4:
                info.type = Double.class;
                info.name = "DiscountPrice";
                break;
            case 5:
                info.type = Double.class;
                info.name = "DiscountPercentage";
                break;
            case 6:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "ReferenceNumber";
                break;
            case 7:
                info.type = Double.class;
                info.name = "PceGrossPrice";
                break;
            case 8:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "ItemId";
                break;
            case 9:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "BrandId";
                break;







 /*
 case 1:
                info.type = Double.class;
                info.name = "TotalNetPrice";
                break;

   case 2:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "ParentProductListRowId";
                break;
            case 6:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "SupplierId";
                break;


            case 9:
                info.type = Double.class;
                info.name = "TotalGrossPrice";
                break;

            case 14:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "PriceType";
                break;
            case 15:
                info.type = Double.class;
                info.name = "WeightedTotalNetPrice";
                break;
            case 16:
                info.type = Long.class;
                info.name = "Barcode";
                break;
            case 17:
                info.type = Long.class;
                info.name = "ConversionId";
                break;
            case 18:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "CreatedByUserId";
                break;
            case 19:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "CreatedDateTime";
                break;
            case 20:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "LastModifiedByUserId";
                break;
            case 21:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "LastModifiedDateTime";
                break;*/

        }
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
