package webservice;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 8/11/2017 5:10:09 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class StoreProductLocationsFilter implements KvmSerializable {

    //    public int companyId;
    public int storeId;
    public int productId;
    //    public int noInventoryDays;
//    public int noOrderPickingDays;
//    public int noReceivedArticleDays;
//    public int noStockMovementDays;
//    public int noStockAdjustmentDays;
//    public int locationLevel1Id;
//    public int locationLevel2Id;
//    public int locationLevel3Id;
//    public int locationLevel4Id;
    public int locationLevel5Id;
//    public boolean isIncludeStats;
//    public WS_Enums.StockAdjustmentType statsStockAdjustmentType;

    public StoreProductLocationsFilter() {
    }

    public StoreProductLocationsFilter(SoapObject soapObject) {
        if (soapObject == null)
            return;
//        if (soapObject.hasProperty("CompanyId")) {
//            Object obj = soapObject.getProperty("CompanyId");
//            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
//                SoapPrimitive j = (SoapPrimitive) obj;
//                companyId = Integer.parseInt(j.toString());
//            } else if (obj != null && obj instanceof Number) {
//                companyId = (Integer) obj;
//            }
//        }
        if (soapObject.hasProperty("StoreId")) {
            Object obj = soapObject.getProperty("StoreId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                storeId = Integer.parseInt(j.toString());
            } else if (obj != null && obj instanceof Number) {
                storeId = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("ProductId")) {
            Object obj = soapObject.getProperty("ProductId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                productId = Integer.parseInt(j.toString());
            } else if (obj != null && obj instanceof Number) {
                productId = (Integer) obj;
            }
        }
//        if (soapObject.hasProperty("NoInventoryDays")) {
//            Object obj = soapObject.getProperty("NoInventoryDays");
//            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
//                SoapPrimitive j = (SoapPrimitive) obj;
//                noInventoryDays = Integer.parseInt(j.toString());
//            } else if (obj != null && obj instanceof Number) {
//                noInventoryDays = (Integer) obj;
//            }
//        }
//        if (soapObject.hasProperty("NoOrderPickingDays")) {
//            Object obj = soapObject.getProperty("NoOrderPickingDays");
//            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
//                SoapPrimitive j = (SoapPrimitive) obj;
//                noOrderPickingDays = Integer.parseInt(j.toString());
//            } else if (obj != null && obj instanceof Number) {
//                noOrderPickingDays = (Integer) obj;
//            }
//        }
//        if (soapObject.hasProperty("NoReceivedArticleDays")) {
//            Object obj = soapObject.getProperty("NoReceivedArticleDays");
//            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
//                SoapPrimitive j = (SoapPrimitive) obj;
//                noReceivedArticleDays = Integer.parseInt(j.toString());
//            } else if (obj != null && obj instanceof Number) {
//                noReceivedArticleDays = (Integer) obj;
//            }
//        }
//        if (soapObject.hasProperty("NoStockMovementDays")) {
//            Object obj = soapObject.getProperty("NoStockMovementDays");
//            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
//                SoapPrimitive j = (SoapPrimitive) obj;
//                noStockMovementDays = Integer.parseInt(j.toString());
//            } else if (obj != null && obj instanceof Number) {
//                noStockMovementDays = (Integer) obj;
//            }
//        }
//        if (soapObject.hasProperty("NoStockAdjustmentDays")) {
//            Object obj = soapObject.getProperty("NoStockAdjustmentDays");
//            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
//                SoapPrimitive j = (SoapPrimitive) obj;
//                noStockAdjustmentDays = Integer.parseInt(j.toString());
//            } else if (obj != null && obj instanceof Number) {
//                noStockAdjustmentDays = (Integer) obj;
//            }
//        }
//        if (soapObject.hasProperty("LocationLevel1Id")) {
//            Object obj = soapObject.getProperty("LocationLevel1Id");
//            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
//                SoapPrimitive j = (SoapPrimitive) obj;
//                locationLevel1Id = Integer.parseInt(j.toString());
//            } else if (obj != null && obj instanceof Number) {
//                locationLevel1Id = (Integer) obj;
//            }
//        }
//        if (soapObject.hasProperty("LocationLevel2Id")) {
//            Object obj = soapObject.getProperty("LocationLevel2Id");
//            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
//                SoapPrimitive j = (SoapPrimitive) obj;
//                locationLevel2Id = Integer.parseInt(j.toString());
//            } else if (obj != null && obj instanceof Number) {
//                locationLevel2Id = (Integer) obj;
//            }
//        }
//        if (soapObject.hasProperty("LocationLevel3Id")) {
//            Object obj = soapObject.getProperty("LocationLevel3Id");
//            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
//                SoapPrimitive j = (SoapPrimitive) obj;
//                locationLevel3Id = Integer.parseInt(j.toString());
//            } else if (obj != null && obj instanceof Number) {
//                locationLevel3Id = (Integer) obj;
//            }
//        }
//        if (soapObject.hasProperty("LocationLevel4Id")) {
//            Object obj = soapObject.getProperty("LocationLevel4Id");
//            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
//                SoapPrimitive j = (SoapPrimitive) obj;
//                locationLevel4Id = Integer.parseInt(j.toString());
//            } else if (obj != null && obj instanceof Number) {
//                locationLevel4Id = (Integer) obj;
//            }
//        }
        if (soapObject.hasProperty("LocationLevel5Id")) {
            Object obj = soapObject.getProperty("LocationLevel5Id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                locationLevel5Id = Integer.parseInt(j.toString());
            } else if (obj != null && obj instanceof Number) {
                locationLevel5Id = (Integer) obj;
            }
        }
//        if (soapObject.hasProperty("IsIncludeStats")) {
//            Object obj = soapObject.getProperty("IsIncludeStats");
//            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
//                SoapPrimitive j = (SoapPrimitive) obj;
//                isIncludeStats = Boolean.parseBoolean(j.toString());
//            } else if (obj != null && obj instanceof Boolean) {
//                isIncludeStats = (Boolean) obj;
//            }
//        }
//        if (soapObject.hasProperty("StatsStockAdjustmentType")) {
//            Object obj = soapObject.getProperty("StatsStockAdjustmentType");
//            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
//                SoapPrimitive j = (SoapPrimitive) obj;
//                statsStockAdjustmentType = WS_Enums.StockAdjustmentType.fromString(j.toString());
//            }
//        }
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
//            case 0:
//                return companyId;
            case 0:
                return storeId;
            case 1:
                return productId;
            case 2:
                return locationLevel5Id;
//            case 3:
//                return noInventoryDays;
//            case 4:
//                return noOrderPickingDays;
//            case 5:
//                return noReceivedArticleDays;
//            case 6:
//                return noStockMovementDays;
//            case 7:
//                return noStockAdjustmentDays;
//            case 8:
//                return locationLevel1Id;
//            case 9:
//                return locationLevel2Id;
//            case 10:
//                return locationLevel3Id;
//            case 11:
//                return locationLevel4Id;
//            case 13:
//                return isIncludeStats;
//            case 14:
//                return statsStockAdjustmentType.toString();
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
//            case 0:
//                info.type = PropertyInfo.INTEGER_CLASS;
//                info.name = "CompanyId";
//                break;
            case 0:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "StoreId";
                break;
            case 1:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "ProductId";
                break;
            case 2:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "LocationLevel5Id";
                break;
            //            case 3:
//                info.type = PropertyInfo.INTEGER_CLASS;
//                info.name = "NoInventoryDays";
//                break;
//            case 4:
//                info.type = PropertyInfo.INTEGER_CLASS;
//                info.name = "NoOrderPickingDays";
//                break;
//            case 5:
//                info.type = PropertyInfo.INTEGER_CLASS;
//                info.name = "NoReceivedArticleDays";
//                break;
//            case 6:
//                info.type = PropertyInfo.INTEGER_CLASS;
//                info.name = "NoStockMovementDays";
//                break;
//            case 7:
//                info.type = PropertyInfo.INTEGER_CLASS;
//                info.name = "NoStockAdjustmentDays";
//                break;
//            case 8:
//                info.type = PropertyInfo.INTEGER_CLASS;
//                info.name = "LocationLevel1Id";
//                break;
//            case 9:
//                info.type = PropertyInfo.INTEGER_CLASS;
//                info.name = "LocationLevel2Id";
//                break;
//            case 10:
//                info.type = PropertyInfo.INTEGER_CLASS;
//                info.name = "LocationLevel3Id";
//                break;
//            case 11:
//                info.type = PropertyInfo.INTEGER_CLASS;
//                info.name = "LocationLevel4Id";
//                break;

//            case 13:
//                info.type = PropertyInfo.BOOLEAN_CLASS;
//                info.name = "IsIncludeStats";
//                break;
//            case 14:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "StatsStockAdjustmentType";
//                break;
        }
    }

//    @Override //    public String getInnerText() { //        return null; //    } // // //    @Override //    public void setInnerText(String s) { //    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
